### PR TITLE
Refactoring main Class

### PR DESCRIPTION
**Pull request by williamscch**
### In this PR, we added some features to apply the SOLID principles:

- We made sure YAGNI, KISS, and DRY rules and Ruby style guide are respected.
- Followed SOLID principles.
- Paid special attention to the "Single-responsibility Principle".
- Make sure that the main.rb is only to start the code and ask the user for the initial choice of options (or to quit).
- Extracted some pieces of logic into separate methods.

### CODE REVIEW

**Review by mikethreels — CHANGES_REQUESTED** [review]
Hi team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- linters are passing

## Required Changes ♻️
- [ ] because there are no changes made in the app.rb file I'm leaving my comments in here.
- [ ] all requests for input and input validation should've been placed in the main.rb file and/or classes/methods whose responsibilities are to request or validate input.
- [ ] in the `create_teacher` and `create_student` methods you are repeating some code please review and make your code more DRY.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by aizjicod** [comment]
@mikethreels but in the project, it says that we need to change the main.rb file that's why we didn't change that file.

**Comment by mikethreels** [comment]
@aizjicod, you are right, however, the requirements also say to make sure the YAGNI, KISS and DRY rules are respected and the SOLID principle is followed, that is what I am referring to

**Comment by aizjicod** [comment]
@mikethreels  the `create_student` and `create_teacher` methods are not repeating themselves since they got different qualifications and there's a necessity for creating those methods. though if you have any other ideas that will help

**Comment by aizjicod** [comment]
and why we should put the validation on the main.rb since its only responsibility is to start the code and the app's initial state. 
though I think it should be better if we create a module for the validations,  what do you think @mikethreels

**Comment by mikethreels** [comment]
@aizjicod, regarding the `create_student` and `create_teacher` methods:
this part of `create_student`
https://github.com/aizjicod/opp-school-library/blob/efdfc4d33ac72d0295f2c068cf51238a27fa5308/app.rb#L120-L122
and this part of `create_teacher`
https://github.com/aizjicod/opp-school-library/blob/efdfc4d33ac72d0295f2c068cf51238a27fa5308/app.rb#L133-L135
are repeating, you can try to join them in `create_person for example`

**Review by t-yanick — APPROVED** [review]
Hi @aizjicod, 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Clean/Organized code
:heavy_check_mark: Descriptive Readme file

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
